const stalls = {
  "Naveen Food Corner": { area:"C & D", description:"Chai, coffee, rusks and quick snacks", prefix:"NFC", icon:"☕", menu:[["Masala Chai",15,"☕"],["Ginger Tea",15,"🍵"],["Coffee",20,"☕"],["Rusk",10,"🥨"],["Biscuits",10,"🍪"],["Veg Puff",25,"🥟"]] },
  "A1 Rama": { area:"C & D", description:"Shakes and evening snacks", prefix:"A1R", icon:"🥤", menu:[["Chocolate Shake",70,"🥤"],["Mango Shake",65,"🥭"],["French Fries",60,"🍟"]] },
  "Roll Corner": { area:"C & D", description:"Chicken, egg and veg rolls", prefix:"RC", icon:"🌯", menu:[["Chicken Roll",70,"🌯"],["Egg Roll",50,"🌯"],["Veg Roll",45,"🌯"]] },
  Monginis: { area:"C & D", description:"Bakery items", prefix:"MON", icon:"🍰", menu:[["Chocolate Pastry",55,"🍰"],["Veg Puff",30,"🥟"],["Cupcake",35,"🧁"]] },
  "Quench Café": { area:"A & B", description:"Shakes and quick bites", prefix:"QC", icon:"🥤", menu:[["Cold Coffee",65,"🥤"],["Oreo Shake",75,"🥤"],["Sandwich",55,"🥪"]] },
  "Anna Café": { area:"A & B", description:"South Indian food", prefix:"AC", icon:"🍛", menu:[["Masala Dosa",60,"🍛"],["Idli",35,"🍚"],["Filter Coffee",25,"☕"]] }
};
let state={page:"home",selected:null,cart:[],pickup:"As soon as ready (10–15 min)",filter:"all",vendorStall:"Naveen Food Corner",lastOrder:null,orders:JSON.parse(localStorage.getItem("acadeats-orders")||"[]")};
const app=document.querySelector("#app"),fmt=n=>`₹${n}`,cartTotal=()=>state.cart.reduce((n,x)=>n+x.price*x.qty,0),cartCount=()=>state.cart.reduce((n,x)=>n+x.qty,0),activeOrders=()=>state.orders.filter(o=>!o.completed);
const saveOrders=()=>localStorage.setItem("acadeats-orders",JSON.stringify(state.orders));
const tones=name=>({"Naveen Food Corner":"peach","A1 Rama":"sky","Roll Corner":"lilac",Monginis:"pink","Quench Café":"yellow","Anna Café":"mint"}[name]);
function setPage(page){state.page=page;document.querySelectorAll(".nav-link").forEach(x=>x.classList.toggle("active",x.dataset.page===page));render();window.scrollTo(0,0)}
function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function stallCard(name){const s=stalls[name];return `<button class="stall-card" onclick="openStall('${name}')"><div class="stall-visual ${tones(name)}"><span>${s.icon}</span><small>${s.area} · Open now</small></div><div class="stall-card-info"><strong>${name}</strong><span>${s.description}</span><div><em>⋆ 4.7</em><b>View menu →</b></div></div></button>`}
function home(){const cd=["Naveen Food Corner","A1 Rama","Roll Corner","Monginis"],ab=["Quench Café","Anna Café"],showCD=state.filter!=="ab",showAB=state.filter!=="cd";return `<section class="home-page"><div class="reference-hero"><div class="reference-copy"><div class="eyebrow">SHIV NADAR UNIVERSITY · STUDENT PROTOTYPE</div><h1>Campus food,<br>all in one place.</h1><p>Browse food stalls across SNU and place your order online.</p><button class="hero-button" onclick="document.querySelector('#stalls').scrollIntoView({behavior:'smooth'})">Explore food stalls</button></div><div class="food-illustration" aria-hidden="true"><i class="spark spark-one">✦</i><i class="spark spark-two">✦</i><div class="sun"></div><div class="bowl"><span>🍛</span></div><div class="ready-pill">SNU campus</div></div></div><div class="feature-rail"><span><i>✦</i> All stalls, one place</span><span><i>●</i> UPI payments</span><span><i>✓</i> Simple order codes</span></div><div class="browse-heading" id="stalls"><div><div class="eyebrow">WHAT'S AVAILABLE</div><h2>Choose a food stall</h2></div><div class="filter-row"><button class="filter ${state.filter==='all'?'active':''}" onclick="setFilter('all')">All locations</button><button class="filter ${state.filter==='cd'?'active':''}" onclick="setFilter('cd')">C & D stalls</button><button class="filter ${state.filter==='ab'?'active':''}" onclick="setFilter('ab')">A & B stalls</button></div></div>${showCD?`<section class="stall-zone"><div class="zone-heading"><h3>C & D Food Stalls</h3><span>Between C Block & D Block · 4 stalls open</span></div><div class="stall-card-grid">${cd.map(stallCard).join("")}</div></section>`:""}${showAB?`<section class="stall-zone"><div class="zone-heading"><h3>A & B Food Stalls</h3><span>Between A Block & B Block · 2 stalls open</span></div><div class="stall-card-grid two-cards">${ab.map(stallCard).join("")}</div></section>`:""}</section>`}
function menu(){const s=stalls[state.selected];return `<button class="back" onclick="setPage('home')">← All food stalls</button><div class="menu-layout"><section><div class="breadcrumb">Food stalls / ${s.area} / ${state.selected}</div><div class="menu-header"><div class="eyebrow">${s.area} FOOD STALLS</div><h1>${state.selected}</h1><p>${s.description}</p></div>${s.menu.map(([name,price,icon])=>`<div class="menu-item"><span class="menu-icon">${icon}</span><div class="item-info"><strong>${name}</strong><span class="price">${fmt(price)}</span></div><button class="add" onclick="addItem('${name}',${price})">Add +</button></div>`).join("")}</section><aside class="cart-box">${cartBox()}</aside></div>`}
function cartBox(){return state.cart.length?`<h3>Your order</h3>${state.cart.map(x=>`<div class="cart-row"><span>${x.qty} × ${x.name}</span><span>${fmt(x.price*x.qty)} <button onclick="removeItem('${x.name}')">×</button></span></div>`).join("")}<div class="total"><span>Total</span><span>${fmt(cartTotal())}</span></div><button class="primary" onclick="setPage('cart')">Checkout</button>`:`<h3>Your order</h3><p class="empty">Add items to continue.</p>`}
function cart(){if(!state.cart.length){setPage("home");return""}const s=stalls[state.selected],n=cartCount();return `<section class="checkout-overlay"><div class="checkout-modal"><button class="checkout-close" onclick="setPage('menu')">×</button><div class="eyebrow">ONE LAST STEP</div><h1>Checkout</h1><div class="checkout-summary"><div><strong>${n} item${n>1?'s':''} in your order</strong><span>${state.cart.map(x=>`${x.qty}× ${x.name}`).join(', ')}</span></div><b>${fmt(cartTotal())}</b></div><label>Pickup location<select><option>${s.area} Food Stalls</option></select></label><label>Pickup time<select onchange="setPickup(this.value)"><option ${state.pickup==='As soon as ready (10–15 min)'?'selected':''}>As soon as ready (10–15 min)</option><option ${state.pickup==='In 20 minutes'?'selected':''}>In 20 minutes</option><option ${state.pickup==='At my next break'?'selected':''}>At my next break</option></select></label><div class="upi-choice"><span>UPI payment</span><small>Google Pay, PhonePe, Paytm</small></div><p class="checkout-note">Your order will be sent to ${state.selected} after payment.</p><button class="checkout-pay" onclick="openUPI()">Continue to UPI</button></div></section>`}
function upi(){return `<section class="checkout-overlay"><div class="upi-modal"><button class="checkout-close" onclick="setPage('cart')">×</button><div class="upi-icon">₹</div><div class="eyebrow">SIMULATED PAYMENT</div><h1>Pay ${fmt(cartTotal())}</h1><p>Payment to <strong>${state.selected}</strong></p><div class="upi-apps"><span>G</span><span>पे</span><span>₹</span></div><button class="checkout-pay" onclick="completePayment()">Confirm payment</button><small>This prototype does not process real payments.</small></div></section>`}
function success(o){return `<section class="success"><div class="success-icon">✓</div><div class="eyebrow">PAYMENT CONFIRMED</div><h1>Order placed</h1><div class="code">${o.code}</div><p>Your order has been sent to <strong>${o.stall}</strong>.</p><p>Pickup time: <strong>${o.pickup}</strong></p><div class="success-summary"><strong>${o.stall}</strong><br>${o.items.map(x=>`${x.qty} × ${x.name}`).join("<br>")}<br><br><strong>Total paid: ${fmt(o.total)}</strong></div><button class="primary" onclick="setPage('orders')">View my order</button><button class="text-button" onclick="setPage('home')">Back to food stalls</button></section>`}
function orders(){const mine=state.orders.filter(o=>o.customer==="Ronit");return `<section class="my-orders"><div class="eyebrow">YOUR ACTIVITY</div><h1>My orders</h1><p class="lead">Orders placed in this browser.</p>${mine.length?`<div class="student-order-list">${mine.map(o=>`<article class="student-order"><div><span class="order-code-mini">${o.code}</span><strong>${o.stall}</strong><p>${o.items.map(x=>`${x.qty} × ${x.name}`).join(', ')}</p><small>Pickup: ${o.pickup}</small></div><div class="student-order-total"><b>${fmt(o.total)}</b><span>${o.completed?'Collected':'Order sent'}</span></div></article>`).join("")}</div>`:`<div class="no-orders">No orders yet. Choose a stall to begin.</div>`}</section>`}
function vendor(){const live=activeOrders().filter(o=>o.stall===state.vendorStall);return `<section class="vendor-main"><div class="vendor-top"><div><div class="eyebrow">acadEats vendor display</div><h1>${state.vendorStall}</h1></div><div class="vendor-time"><span class="live-dot"></span> LIVE ORDERS<br><span id="clock"></span></div></div><div class="vendor-controls"><label>Outlet<select onchange="setVendorStall(this.value)">${Object.keys(stalls).map(n=>`<option ${n===state.vendorStall?'selected':''}>${n}</option>`).join("")}</select></label><button onclick="seedDemoOrder()">Add demo order</button></div><div class="vendor-note">Paid orders appear here automatically. Call the code when the order is ready.</div><div class="order-board">${live.length?live.map((o,i)=>`<article class="vendor-order ${i===0?'new':''}"><div>${i===0?'<div class="new-label">New order</div>':''}<div class="vendor-code">${o.code}</div></div><div class="vendor-details"><strong>${o.customer}</strong><span>${o.items.map(x=>`${x.qty} × ${x.name}`).join(', ')}</span><span>${o.pickup} · ${o.time}</span></div><button class="clear" onclick="completeOrder('${o.id}')">Collected</button></article>`).join(""):`<div class="no-orders">No live orders for this outlet.</div>`}</div></section>`}
function render(){const pages={home,menu,cart,upi,success:()=>success(state.lastOrder),orders,vendor};app.innerHTML=pages[state.page]();updateHeader();if(state.page==='vendor')updateClock()}
function updateHeader(){const n=activeOrders().filter(o=>o.customer==='Ronit').length;document.querySelector('.profile').textContent=n?`My order · ${n}`:'My order'}
function updateClock(){const x=document.querySelector('#clock');if(x)x.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function setFilter(x){state.filter=x;render()}function setPickup(x){state.pickup=x}function setVendorStall(x){state.vendorStall=x;render()}function openStall(x){state.selected=x;state.cart=[];state.pickup="As soon as ready (10–15 min)";setPage('menu')}function addItem(name,price){const x=state.cart.find(i=>i.name===name);x?x.qty++:state.cart.push({name,price,qty:1});render();toast(`${name} added`)}function removeItem(name){const x=state.cart.find(i=>i.name===name);if(x.qty>1)x.qty--;else state.cart=state.cart.filter(i=>i.name!==name);render()}function openUPI(){setPage('upi')}
function completePayment(){const s=stalls[state.selected],o={id:crypto.randomUUID(),code:`${s.prefix}-${Math.floor(100+Math.random()*900)}`,stall:state.selected,customer:'Ronit',items:state.cart,pickup:state.pickup,total:cartTotal(),time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),completed:false};state.orders.unshift(o);saveOrders();state.lastOrder=o;state.cart=[];setPage('success')}
function completeOrder(id){state.orders=state.orders.map(o=>o.id===id?{...o,completed:true}:o);saveOrders();render();toast('Order marked as collected')}
function seedDemoOrder(){const s=stalls[state.vendorStall],[name,price]=s.menu[0];state.orders.unshift({id:crypto.randomUUID(),code:`${s.prefix}-${Math.floor(100+Math.random()*900)}`,stall:state.vendorStall,customer:'Demo student',items:[{name,price,qty:1}],pickup:'As soon as ready',total:price,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),completed:false});saveOrders();render()}
window.addEventListener('storage',e=>{if(e.key==='acadeats-orders'){state.orders=JSON.parse(e.newValue||'[]');render()}});document.querySelectorAll('.nav-link').forEach(x=>x.addEventListener('click',()=>setPage(x.dataset.page)));document.querySelector('#home-button').addEventListener('click',()=>setPage('home'));document.querySelector('.profile').addEventListener('click',()=>setPage('orders'));render();
